### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by usama7628674** [Anapher/Maze#7]
@Anapher 
![Capture](https://user-images.githubusercontent.com/29252277/65949119-080e0380-e455-11e9-83a1-2e1f6e3ed1fe.PNG)

I've all .net framework versions installed as well
![Capture1](https://user-images.githubusercontent.com/29252277/65949182-1fe58780-e455-11e9-898c-44cf809329bf.PNG)

![Capture3](https://user-images.githubusercontent.com/29252277/65949198-25db6880-e455-11e9-8a66-51ba93e771f4.PNG)

**Comment by H4xl0r** [comment]
Just google the error ....
https://www.microsoft.com/en-us/download/details.aspx?id=3556 

patch your net ?

**Comment by usama7628674** [comment]
Now i'm getting this
![Capture](https://user-images.githubusercontent.com/29252277/66255222-a9b98b80-e79a-11e9-89e5-6640f48233e7.PNG)

**Comment by Chordp** [comment]
The same problem, have you solved it?

**Comment by usama7628674** [comment]
@Chordp No

**Comment by H4xl0r** [comment]
same problem here Something related to TreeViewEx

**Comment by H4xl0r** [comment]
@Chordp @usama7628674 
Fixed it via 

1. opening \Maze\src\submodules\TreeViewEx\TreeViewEx.sln in studio and update the nuget packs
from both treeview  and  treeview.test (rightclick on the projet folder go to nuget packs ... switch source from maze to all and update ... )

2.Rebuild the project 

<PackageReference Include="Nito.AsyncEx" Version="5.0.0" />

**Comment by Chordp** [comment]
> @Chordp @ usama7628674
> 通过修复它
> 
> 1. 在Studio中打开\ Maze \ src \ submodules \ TreeViewEx \ TreeViewEx.sln并
>    从treeview和treeview.test 更新nuget包（在projet文件夹上单击鼠标右键转到nuget packs ...将源从迷宫切换到全部并更新.. ）
> 
> 2.重建项目
> 
> 获取
> https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2019Extension

Thank you, but it's still the same

`C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(243,9): error MC1000: 未知的生成错误“Could not find assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.”`

**Comment by H4xl0r** [comment]
strange one 
i am running fine with downloading the repo via git command shown in the readme
then i am opening the folder maze and go to the \ Maze \ src \ submodules \ TreeViewEx \ TreeViewEx.sln
open it up with visual and update nugets for both ...rebuild the project.
then go on with fake build 
runs fine 
!
will attach video soon

**Comment by H4xl0r** [comment]
@Anapher could you please reply we need the infos , inside the old https://nuget.mazeadmin.com/api/v3/index.json
its offline .... 

or could you explain how to add the packages to the server 
got all running server client admin
with a workaround around https://nuget.mazeadmin.com/api/v3/index.json
but now the server eg admin panel is missing most packages !

**Comment by Chordp** [comment]
> 奇怪的一个
> 我运行良好，可以通过自述
> 文件中显示的git命令下载回购协议，然后打开迷宫文件夹，然后转到\ Maze \ src \ submodules \ TreeViewEx \ TreeViewEx.sln
> ，通过可视化方式打开它，并为两者更新nuget ...重建项目。
> 然后继续进行伪造
> 运行
> ！
> 视频👍
> https://streamable.com/js5dk
> 
> 我们需要找到旧的信息
> “ https://nuget.mazeadmin.com/api/v3/index.json ”

Thank you, your video, built successfully

**Comment by H4xl0r** [comment]
you will need 
to change the server also to get it running , the server asks for nuget packages on a nugetserver but the server is down (https://nuget.mazeadmin.com/api/v3/index.json) or must be self 
hosted i guess , waiting for explainiation from @Anapher 
how to put the modules into the server ? (whats was inside the index.json there ?)
how to server the packages to the server ?

Temp workaround :

open Maze/src/Maze.Server/appsettings.json  and change
 "PrimarySources": [ "https://nuget.mazeadmin.com/api/v3/index.json" ],
to 
"PrimarySources": [ "https://www.myget.org/F/maze/api/v3/index.json" ],

sure its a messy workaround ! modules will miss !
but the server runs the admin runs and the client connects !

Also you need to fix the ports from the client and server to be the same like http://localhost:5000.

**Comment by Chordp** [comment]
> 您还需要
> 更改服务器以使其运行，服务器在nugetserver上请求nuget软件包，但是服务器已关闭（https://nuget.mazeadmin.com/api/v3/index.json）或必须为self
> 我猜是托管的，正在等待@Anapher的解释
> 如何将模块放入服务器？（什么地方在index.json里面？）
> 如何将程序包服务器存储到服务器？
> 
> 临时解决方法：
> 
> 打开Maze / src / Maze.Server / appsettings.json并将
> “ PrimarySources”：[“ https://nuget.mazeadmin.com/api/v3/index.json”] 更改
> 为
> “ PrimarySources”：[“ https：/ /www.myget.org/F/maze/api/v3/index.json“]，
> 
> 确保它是一个凌乱的解决方法！模块会错过！
> 但是服务器运行管理员运行，客户端连接！
> 
> 另外，您需要将客户端和服务器的端口固定为相同的端口，例如[http：// localhost：5000](http://localhost:5000)



> you will need
> to change the server also to get it running , the server asks for nuget packages on a nugetserver but the server is down (https://nuget.mazeadmin.com/api/v3/index.json) or must be self
> hosted i guess , waiting for explainiation from @Anapher
> how to put the modules into the server ? (whats was inside the index.json there ?)
> how to server the packages to the server ?
> 
> Temp workaround :
> 
> open Maze/src/Maze.Server/appsettings.json and change
> "PrimarySources": [ "https://nuget.mazeadmin.com/api/v3/index.json" ],
> to
> "PrimarySources": [ "https://www.myget.org/F/maze/api/v3/index.json" ],
> 
> sure its a messy workaround ! modules will miss !
> but the server runs the admin runs and the client connects !
> 
> Also you need to fix the ports from the client and server to be the same like http://localhost:5000

So, can't we add modules?

**Comment by H4xl0r** [comment]
im on it 
will come back with infos

**Comment by H4xl0r** [comment]
we need the old packages nuget from the old server , hopefully @Anapher  will help !

**Comment by Anapher** [comment]
The readme was just updated.
